[Fix] Update testflight-deploy.yml (#109)

diff --git a/.github/workflows/testflight-deploy.yml b/.github/workflows/testflight-deploy.yml
--- a/.github/workflows/testflight-deploy.yml
+++ b/.github/workflows/testflight-deploy.yml
@@ -9,7 +9,7 @@ on:
 jobs:
   deploy:
     name: Deploy Testflight
-    runs-on: macos-latest
+    runs-on: macos-15.2
     
     env:
       CI: true
@@ -35,17 +35,37 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0  # 모든 히스토리와 태그 가져오기
+
+      - name: Set Xcode version
+        uses: maxim-lobanov/setup-xcode@v1
+        with:
+          xcode-version: '16.2'
+          
+      - name: Force switch to Xcode 16.2
+        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
+
+      - name: Check actual Xcode version and fail if not 16.2
+        run: |
+          echo "🔍 Checking Xcode version..."
+          XCODE_VERSION=$(xcodebuild -version | grep Xcode | awk '{ print $2 }')
+          echo "🐿️ Detected Xcode version: $XCODE_VERSION"
       
+          if [[ "$XCODE_VERSION" != "16.2" ]]; then
+            echo "❌ Error: Expected Xcode 16.2 but got $XCODE_VERSION"
+            exit 1
+          else
+            echo "😽 Xcode 16.2 is correctly set."
+          fi
+
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
-          ruby-version: '3.0'
+          ruby-version: '3.2'
           bundler-cache: true
-      
+
       - name: Install dependencies
-        run: |
-          gem install bundler
-          bundle install
+        working-directory: ./ACON-iOS
+        run: bundle install
       
       - name: Set up Git credentials for match
         uses: webfactory/ssh-agent@v0.7.0
@@ -53,6 +73,7 @@ jobs:
           ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
       
       - name: Deploy to TestFlight
+        working-directory: ./ACON-iOS
         run: bundle exec fastlane beta
         env:
           ENVIRONMENT: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-prod') && 'production' || 'development' }}
